name: phpunit

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:

    static:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3
            -   uses: php-actions/composer@v6
            -   uses: php-actions/phpstan@v3
                with:
                    path: src/
                    level: 5

    phpunit:

        runs-on: ubuntu-latest
        needs: static
        strategy:
            matrix:
                php-versions: [ '7.4', '8.0', '8.1', '8.2' ]

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}

            -   uses: php-actions/composer@v6

            -   name: Run test suite
                run: composer run-script test

    coverage-badge:
        needs: phpunit
        runs-on: ubuntu-latest
        steps:

            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.2

            -   uses: php-actions/composer@v6

            -   name: Run test suite
                run: composer run-script test
            -   name: phpunit-coverage-badge
                uses: timkrase/phpunit-coverage-badge@v1.2.0
                with:
                    push_badge: true
                    repo_token: ${{ secrets.GITHUB_TOKEN }}
